spring.application.name=ecommerce

# Registrando datos de conexion a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=pedro
spring.datasource.password=duoc123

# Configurando parametros de hibernate e indicando MariaDB nativo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect